server:
  port: 8064
  servlet:
    context-path: /ai
spring:
  ai:
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json
    deepseek:
      api-key: ${DS_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
      embedding: false
    model:
      embedding: false
      image: false
