server:
  port: 8062
  servlet:
    context-path: /ai
spring:
  ai:
    zhipuai:
      api-key: ${ZP_API_KEY}
      base-url: https://open.bigmodel.cn/api/paas/
      chat:
        options:
          model: glm-4-plus
    openai:
      api-key: ${DS_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
      embedding: false
    model:
      embedding: false
      image: false
